INSERT INTO GRANA (IME) VALUES
  ('Grana 1'),
  ('Grana 2');

-- INSERT INTO PODGRANA (IME) VALUES ();

-- INSERT INTO KORISNIK(ADMIN, ADRESA, EMAIL, IME, KORISNICKO_IME, OSOBNI_STATUS, PREZIME, TELEFON, ZAPORKA, ZVANJE, GRANA_ID, PODGRANA_ID) VALUES ();

-- INSERT INTO UMJETNINA (DATUM_NASTANKA, IME, TEHNIKA) VALUES ();